# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('room_title', models.CharField(max_length=200)),
                ('room_slug', models.SlugField(blank=True, null=True)),
                ('room_condition', models.CharField(choices=[('Dirty', 'Dirty'), ('Clean', 'Clean'), ('Active', 'Active'), ('Maintenance', 'Maintenance'), ('DNR', 'DNR')], max_length=15)),
                ('room_amount', models.IntegerField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, max_length=200, null=True)),
                ('room_image', models.FileField(blank=True, null=True, upload_to='room/%Y/%m/%d')),
                ('room_timestamp', models.DateTimeField(blank=True, null=True)),
                ('room_utimestamp', models.DateTimeField(blank=True, null=True)),
                ('room_track', models.TextField(blank=True)),
                ('room_utrack', models.TextField(blank=True)),
                ('room_history', models.TextField(blank=True)),
                ('room_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=15)),
                ('room_sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Staff', verbose_name='Assign To Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_title', models.CharField(max_length=100)),
                ('room_type_slug', models.SlugField(blank=True, null=True)),
                ('room_type_facilities', models.TextField(blank=True)),
                ('room_type_price', models.IntegerField()),
                ('room_type_image', models.FileField(null=True, upload_to='room_type/%Y/%m/%d')),
                ('room_type_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_type_utimestamp', models.DateTimeField(blank=True, null=True)),
                ('room_type_track', models.TextField(blank=True)),
                ('room_type_utrack', models.TextField(blank=True)),
                ('room_type_number', models.IntegerField(blank=True)),
                ('room_title_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('room_type_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.Room_type'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
