# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('folio_id', models.AutoField(primary_key=True, serialize=False)),
                ('folio_title', models.CharField(blank=True, max_length=111)),
                ('folio_unit', models.IntegerField(blank=True, default=0)),
                ('folio_price', models.FloatField(blank=True, default=0)),
                ('folio_amount', models.FloatField(blank=True)),
                ('folio_tax', models.FloatField(blank=True, default=0)),
                ('folio_total', models.FloatField(blank=True)),
                ('folio_discount', models.FloatField(blank=True, default=0)),
                ('folio_disc_res', models.TextField(blank=True)),
                ('folio_from', models.CharField(choices=[('Room', 'Room'), ('Damage', 'Damage'), ('Restaurant', 'Restaurant'), ('Spa', 'Spa'), ('Bar', 'Bar'), ('Others', 'Others')], default='Room', max_length=55)),
                ('folio_receipt', models.CharField(blank=True, max_length=55)),
                ('folio_description', models.TextField(blank=True)),
                ('folio_invoice', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=55)),
                ('folio_type', models.CharField(blank=True, max_length=55)),
                ('folio_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('folio_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('folio_ueid', models.IntegerField(blank=True)),
                ('folio_track', models.TextField(blank=True, null=True)),
                ('folio_utrack', models.TextField(blank=True, null=True)),
                ('folio_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('folio_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('folio_gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_customer', models.CharField(blank=True, max_length=55, null=True)),
                ('payment_amount', models.FloatField(blank=True)),
                ('payment_tax', models.FloatField(blank=True, default=0)),
                ('payment_total', models.FloatField(blank=True)),
                ('payment_discount', models.FloatField(blank=True, default=0)),
                ('payment_disc_res', models.TextField(blank=True)),
                ('payment_from', models.CharField(choices=[('Room', 'Room'), ('Damage', 'Damage'), ('Restaurant', 'Restaurant'), ('Spa', 'Spa'), ('Bar', 'Bar'), ('Others', 'Others')], default='Room', max_length=55)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('POS', 'POS'), ('Revenue Loss', 'Revenue Loss'), ('Others', 'Others')], default='Cash', max_length=55)),
                ('payment_receipt', models.CharField(blank=True, max_length=55)),
                ('payment_description', models.TextField(blank=True)),
                ('payment_invoice', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=55)),
                ('payment_type', models.CharField(blank=True, max_length=55)),
                ('payment_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_ueid', models.IntegerField(blank=True, default=0)),
                ('payment_track', models.TextField(blank=True, null=True)),
                ('payment_utrack', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('payment_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('payment_gid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.Guest')),
            ],
        ),
    ]
