# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('Guest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_nubmer', models.IntegerField()),
                ('equipment_title', models.CharField(max_length=50)),
                ('equipment_slug', models.SlugField()),
                ('equipment_type', models.CharField(choices=[('Chair', 'Chair'), ('Bed', 'Bed')], default='Chair', max_length=50)),
                ('equipment_specification', models.TextField(blank=True, null=True)),
                ('equipment_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment_ueid', models.IntegerField(blank=True, null=True)),
                ('equipment_track', models.TextField(blank=True, null=True)),
                ('equipment_utrack', models.TextField(blank=True, null=True)),
                ('equipment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=50)),
                ('equipment_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_customer', models.CharField(max_length=111)),
                ('service_price', models.FloatField(blank=True, null=True)),
                ('service_discount', models.FloatField(blank=True, null=True)),
                ('service_tax', models.FloatField(blank=True, null=True)),
                ('service_total', models.FloatField(blank=True, null=True)),
                ('service_extra', models.TextField(blank=True, null=True)),
                ('service_from', models.CharField(choices=[('Direct', 'Direct'), ('Call', 'Call')], default='Direct', max_length=50)),
                ('service_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_ueid', models.IntegerField(blank=True, null=True)),
                ('service_track', models.TextField(blank=True, null=True)),
                ('service_utrack', models.TextField(blank=True, null=True)),
                ('service_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=50)),
                ('service_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('service_eid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.Equipment')),
                ('service_gid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Service_history',
            fields=[
                ('serviceh_id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceh_sid', models.CharField(max_length=111)),
                ('serviceh_customer', models.CharField(blank=True, max_length=111, null=True)),
                ('serviceh_spas', models.TextField()),
                ('serviceh_prices', models.TextField()),
                ('serviceh_units', models.TextField()),
                ('serviceh_amount', models.TextField()),
                ('serviceh_discount', models.FloatField(default=0)),
                ('serviceh_tax', models.FloatField(blank=True, null=True)),
                ('serviceh_total', models.FloatField(default=0)),
                ('serviceh_description', models.TextField(blank=True, null=True)),
                ('serviceh_from', models.CharField(choices=[('Direct', 'Direct'), ('Call', 'Call')], default='Direct', max_length=50)),
                ('serviceh_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('serviceh_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('serviceh_ueid', models.IntegerField(blank=True, null=True)),
                ('serviceh_track', models.TextField(blank=True, null=True)),
                ('serviceh_utrack', models.TextField(blank=True, null=True)),
                ('serviceh_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=50)),
                ('serviceh_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('serviceh_eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa.Equipment')),
                ('serviceh_gid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.Guest')),
                ('serviceh_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('spa_id', models.AutoField(primary_key=True, serialize=False)),
                ('spa_title', models.CharField(max_length=111)),
                ('spa_slug', models.SlugField()),
                ('spa_price', models.FloatField(blank=True, null=True)),
                ('spa_discount', models.FloatField(blank=True, null=True)),
                ('spa_tax', models.FloatField(blank=True, null=True)),
                ('spa_special', models.CharField(max_length=111)),
                ('spa_extra', models.TextField(blank=True, null=True)),
                ('spa_description', models.TextField(blank=True, null=True)),
                ('spa_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('spa_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('spa_ueid', models.IntegerField(blank=True, null=True)),
                ('spa_track', models.TextField(blank=True, null=True)),
                ('spa_utrack', models.TextField(blank=True, null=True)),
                ('spa_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spa_type',
            fields=[
                ('spa_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('spa_type_title', models.CharField(max_length=50)),
                ('spa_type_slug', models.SlugField()),
                ('spa_type_description', models.TextField(blank=True, null=True)),
                ('spa_type_discount', models.IntegerField()),
                ('spa_type_tax', models.FloatField(default=0)),
                ('spa_type_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('spa_type_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('spa_type_ueid', models.IntegerField(blank=True, null=True)),
                ('spa_type_track', models.TextField(blank=True, null=True)),
                ('spa_type_utrack', models.TextField(blank=True, null=True)),
                ('spa_type_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=50)),
                ('spa_type_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spa',
            name='spa_stid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa.Spa_type'),
        ),
        migrations.AddField(
            model_name='spa',
            name='spa_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='service_spid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa.Spa'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
