# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 05:07
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_cron',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_from', models.EmailField(max_length=100)),
                ('email_to', models.EmailField(max_length=100)),
                ('email_subject', models.CharField(max_length=222)),
                ('email_body', ckeditor.fields.RichTextField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_purpose', models.CharField(choices=[('Login', 'Login'), ('Register', 'Register'), ('Booking', 'Booking'), ('Payment', 'Payment'), ('Checkout', 'Checkout'), ('Cancellation', 'Cancellation'), ('Invoice', 'Invoice'), ('feedback', 'feedback')], default='Login', max_length=10)),
                ('email_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_utimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_track', models.TextField(blank=True)),
                ('email_utrack', models.TextField(blank=True)),
                ('email_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('email_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
